addons:
  apt:
    packages:
    - graphviz
before_install:
- echo "before_install"
branches:
  only:
  - master
  - develop
  - build_on_trivasci
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.sonar/cache"
env:
  global:
  - CI_BUILD_REF_NAME=$TRAVIS_BRANCH
  - GIT_SERVICE=https://github.com
  - INFRASTRUCTURE=github
  - MAVEN_SKIP_RC=true
install: true
jdk:
- oraclejdk8
language: java
script:
- echo "on_every_push"
- bash ci.sh test_and_build
#- bash ci.sh publish_snapshot
#- bash ci.sh deploy_maven_site
services:
- docker
sudo: required
